version: '3'
services:
  postgres:
    image: ${DOCKER_REGISTRY}/postgres:15.2-alpine
    container_name: postgresql
    environment:
      - POSTGRES_DB=artifactory
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=c4erlaZIl0kXUYD7rA7jU7YRyesgcm256.MsSAdfhbaHBSJDV.a_dOSZHVuYBzAyTxGbt2aU6U
    expose:
      - 5432:5432
    networks:
      - jfrog
    volumes:
      - ${ROOT_DATA_DIR}/var/data/postgres/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
networks:
  jfrog:
    name: jfrog_backend