version: '3.4'

services:
  traefik:
    image: "traefik:v2.4"
    container_name: "traefik-router"
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.traefik=true"
    networks:
      - traefik
    ports:
      # HTTPS / SSL port
      - "80:80"
      - "443:443"
      # The Traefik Web UI port (enabled by api:insecure: true in traefik.yml)
      - "8080:8080"
    volumes:
     - ./traefik.yml:/etc/traefik/traefik.yml:ro
     - ./config.yml:/etc/traefik/config.yml:ro
     - ./letsencrypt:/letsencrypt
     - /var/run/docker.sock:/var/run/docker.sock:ro
networks:
  traefik:
    name: traefik_backend