global:
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false

  file:
    filename: /etc/traefik/config.yml
    watch: true

certificatesresolvers:
  acmestg:
    acme:
      tlschallenge: true
      email: "swissarmybud@gmail.com"
      storage: "/letsencrypt/acme.json"
      caserver: "https://acme-staging-v02.api.letsencrypt.org/directory"
  acmeprd:
    acme:
      tlschallenge: true
      email: "swissarmybud@gmail.com"
      storage: "/letsencrypt/acme.json"
      caserver: "https://acme-v02.api.letsencrypt.org/directory"

log:
  level: DEBUG
  format: common

entryPoints:
  web:
    address: ":80"
#    http:
#      redirections:
#        entryPoint:
#          to: https
#          scheme: https
  websecure:
    address: ":443"